"""Track B -- SEO (Linchpin 3.0 plan section 8). First module: ``crawl_audit``
(S1 technical SEO audit checks, PR-22). Later PRs add ``schema_gen``/``feeds``/
``llms_txt`` (S2), ``pdp_writer`` (S3), and ``geo_probe`` (S5) alongside it.
"""

from __future__ import annotations

from .crawl_audit import (
    BROKEN_INTERNAL_LINK,
    DUPLICATE_CONTENT,
    DUPLICATE_META_DESCRIPTION,
    DUPLICATE_TITLE,
    ISSUE_TYPES,
    MALFORMED_STRUCTURED_DATA,
    MISSING_ALT_TEXT,
    MISSING_CANONICAL,
    MISSING_META_DESCRIPTION,
    MISSING_STRUCTURED_DATA,
    MISSING_TITLE,
    ROBOTS_TXT_MISSING,
    ROBOTS_TXT_SUSPICIOUS,
    SITEMAP_MISSING,
    SITEMAP_SUSPICIOUS,
    CrawledPage,
    Finding,
    ImageRef,
    RobotsTxtCheck,
    SitemapCheck,
    check_robots_txt,
    check_sitemap_xml,
    find_broken_internal_links,
    find_duplicate_content,
    find_duplicate_meta_descriptions,
    find_duplicate_titles,
    find_missing_alt_text,
    find_missing_canonical,
    find_missing_meta_descriptions,
    find_missing_titles,
    find_structured_data_issues,
    robots_and_sitemap_findings,
    run_checks,
)

__all__ = [
    "BROKEN_INTERNAL_LINK",
    "DUPLICATE_CONTENT",
    "DUPLICATE_META_DESCRIPTION",
    "DUPLICATE_TITLE",
    "ISSUE_TYPES",
    "MALFORMED_STRUCTURED_DATA",
    "MISSING_ALT_TEXT",
    "MISSING_CANONICAL",
    "MISSING_META_DESCRIPTION",
    "MISSING_STRUCTURED_DATA",
    "MISSING_TITLE",
    "ROBOTS_TXT_MISSING",
    "ROBOTS_TXT_SUSPICIOUS",
    "SITEMAP_MISSING",
    "SITEMAP_SUSPICIOUS",
    "CrawledPage",
    "Finding",
    "ImageRef",
    "RobotsTxtCheck",
    "SitemapCheck",
    "check_robots_txt",
    "check_sitemap_xml",
    "find_broken_internal_links",
    "find_duplicate_content",
    "find_duplicate_meta_descriptions",
    "find_duplicate_titles",
    "find_missing_alt_text",
    "find_missing_canonical",
    "find_missing_meta_descriptions",
    "find_missing_titles",
    "find_structured_data_issues",
    "robots_and_sitemap_findings",
    "run_checks",
]
